development:
  adapter: async

test:
  adapter: async

production:
  adapter: async
  <%# adapter: redis %>
  <%# url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %1> %>
  <%# channel_prefix: underscore-as-a-service_production %>
